import Head from 'next/head';
import Dashboard from '../components/Dashboard';
import Login from '../components/Login';
import { ContactsProvider } from '../lib/context/ContactsProvider';
import { ConversationsProvider } from '../lib/context/ConversationsProvider';
import { SocketProvider } from '../lib/context/SocketProvider';

import useLocalStorage from '../lib/useLocalStorage';

const Home = () => {
  const [id, setId] = useLocalStorage('id');

  const dashboard = (
    <SocketProvider id={id}>
      <ContactsProvider>
        <ConversationsProvider id={id}>
          <Dashboard className="dashboard" id={id} />
        </ConversationsProvider>
      </ContactsProvider>
    </SocketProvider>
  );

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {id ? dashboard : <Login onIdSubmit={setId} />}
    </>
  );
};

export default Home;
